### ISSUE TITLE
CLI interface?

### ISSUE THREAD

**Issue by davegaeddert** [dropseed/configyaml#4]
I had someone ask again whether or not there was some kind of linter or something they could use for pullapprove config. I asked how he would use it ideally, and he said a command on the command line. Not totally sure if I agree (curl-ing a file to a url / api almost seems easier), but it would be possible. Especially if your ConfigLoader is now an extractable component, with no real secrets in it. You could `pip install sibbell-config`  then `sibbell_config validate .sibbell.yml`

**Comment by davegaeddert** [comment]
@paulortman if you get through everything else before I'm ready with other stuff, just as well give this a try since we have the cli part in there now? Some basic command to validate a file or stdin?

**Comment by paulortman** [comment]
@davegaeddert 

So are you thinking that a cli interface would look something like:

`configyaml <dotted.path.to.custom.CustomConfigLoaderClass> some/config/file.yaml`

At least that's about the only way I've been able to think of a generic method for having a cli...

**Comment by davegaeddert** [comment]
Yeah good point. I hadn't totally thought that through.

Maybe let's just ignore this for now until we know and are actually ready for it, but I'm guessing it will be either:
1. All cli functionality will be in the package that uses this (`sibbell`) and none of that will be in here
1. This will have a base cli that gets extended by whatever uses it to provide a cli of its own. That's what I am doing here (https://github.com/dropseedlabs/project-cli) but I haven't completely nailed that down yet... Basically it provides a set of core commands and utility classes that apply to anything that uses it, and then for each project you make a simple extension of it and add any additional commands.
